/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8d21MsEaFrjU1q6tvNDHvf

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariants_9Hyy9KzWn8QX } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 9hyy9kzWn8qX/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariants_9Hyy9KzWn8QX
});
